min_log_level: "debug"
jwt_secret: "jwt_secret"
http_server:
  port: 5010
  read_timeout: 10
  write_timeout: 5
grpc_server:
  port: 5011
postgresql:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  name: "auth"
redis:
  host: "localhost"
  port: 6379
