min_log_level: "debug"
jwt_secret: "jwt_secret"
grpc_server:
  port: 5011
http_server:
  port: 5012
postgresql:
  host: "localhost"
  port: 5454
  user: "user"
  password: "password"
  name: "name"
redis:
  host: "localhost"
  port: 6379
rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue_name: "notify_telegram_auth"
  durable: true
  auto_delete: false
  exclusive: false
  no_wait: false
telegram_token: "234:dssfdFDSf"
