min_log_level: "debug"
jwt_secret: "jwt_secret"
grpc_server:
  port: 5011
http_server:
  port: 5012
swagger_server:
  port: 5013
postgresql:
  host: "localhost"
  port: 5454
  user: "user"
  password: "password"
  name: "name"
redis:
  host: "localhost"
  port: 6379
