services:
  mbs-auth:
    build:
      dockerfile: local.Dockerfile
    container_name: mbs-auth-container
    volumes:
      - .:/app
    restart: always
    ports:
      - "5011:5011"
      - "5012:5012"
    networks:
      - mbs

networks:
  mbs:
    name: mbs
    external: true
